### ISSUE TITLE
PopcBuffer only shows the 1st file when multiple files are on command line

### ISSUE THREAD

**Issue by jeebak** [yehuohan/popc#1]
Thank you for creating this alternative to `vim-ctrlspace`! I'm enjoying `popc` so far, but I ran into a bug.

When I start vim with multiple files on the command line, for example:

```
vim file1.txt file2.txt file3.txt
```

when I call `:PopcBuffer`, only the 1st file is listed. Running `:buffers` does show all of the expected files, by comparison.

**Comment by yehuohan** [comment]
Thank your reported issue. It's indeep a use case I didn't catch before.
